<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Documentation</name>
   <tag></tag>
   <elementGuidId>0979abd4-8568-4d02-a207-d4918dbb7d92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_navigation-primary']/nav/ul/li[3]/ul/li/ul/li/a/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.title_item_company</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f1af7f91-15ba-4a40-80c6-76a423b507cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title_item_company</value>
      <webElementGuid>04b205e5-7123-479a-aed1-50cdb676bccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documentation</value>
      <webElementGuid>d56f5db1-7ce6-4b46-adaa-1e86bcc6dd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_navigation-primary&quot;)/nav[@class=&quot;navigation-primary&quot;]/ul[@class=&quot;submenu level-1&quot;]/li[@class=&quot;has-submenu menu-item Resources&quot;]/ul[@class=&quot;submenu level-2&quot;]/li[@class=&quot;has-submenu menu-item Support&quot;]/ul[@class=&quot;submenu level-3&quot;]/li[@class=&quot;no-submenu menu-item Documentation&quot;]/a[@class=&quot;menu-link&quot;]/div[@class=&quot;item_company&quot;]/div[@class=&quot;include_icon_title&quot;]/div[@class=&quot;description_item_company&quot;]/div[@class=&quot;title_item_company&quot;]</value>
      <webElementGuid>343d24c5-fc75-4e99-926b-75b26670f212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_navigation-primary']/nav/ul/li[3]/ul/li/ul/li/a/div/div/div[2]/div</value>
      <webElementGuid>7c6c953d-1bd7-457f-a233-ae12391d4955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/following::div[5]</value>
      <webElementGuid>b18a537b-d835-4850-ab5c-95a2bab6c5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/following::div[5]</value>
      <webElementGuid>b72eaa96-1105-4933-9f2a-f6cbf14bd2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[1]/preceding::div[2]</value>
      <webElementGuid>ba42b083-77a8-4548-9bcf-73fd003e7ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repository'])[1]/preceding::div[7]</value>
      <webElementGuid>c65c5897-b64d-498e-a39f-184b9c965162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Documentation']/parent::*</value>
      <webElementGuid>6a225d36-1563-47bb-867e-d842202d99f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/div[2]/div</value>
      <webElementGuid>5a2d33ea-4f2c-4657-9e83-b699baa52948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Documentation' or . = 'Documentation')]</value>
      <webElementGuid>21edbade-f890-4b86-b110-6bfd269fb058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
