<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alert Box Examples_confirmexample</name>
   <tag></tag>
   <elementGuidId>cc59ab1d-7380-4f76-8241-3afc2fa4fcd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmexample']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmexample</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5e97a0e-7239-4ed1-8225-3f1a0f9037a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled-click-button</value>
      <webElementGuid>b66b88e1-4541-49fd-be2f-6c3dbf4f87be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmexample</value>
      <webElementGuid>a9766659-5a1e-4f3c-9a25-8a148e7dbcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fd7a380-eac9-41f6-adbf-b5fe878b069b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_confirm()</value>
      <webElementGuid>9a2f1d18-fb7c-4046-ade4-b9326800700b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show confirm box</value>
      <webElementGuid>82174181-de8b-448b-8ca2-efdab00440d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmexample&quot;)</value>
      <webElementGuid>8a9dbf3f-6067-4ede-ad30-7209af9dff40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmexample']</value>
      <webElementGuid>18f83a01-df44-4ffb-a9fd-52f72f3b9ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>dfa3913d-49fe-442f-b579-f3bfade8b1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmexample' and @type = 'button']</value>
      <webElementGuid>928b096d-8493-4b5a-b512-808d2d220247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
