<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Katalon TestOps</name>
   <tag></tag>
   <elementGuidId>52fcdc61-a4e7-42e8-9942-99463f16c7e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='jsTOCHorizontal']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>519995e6-875d-4a52-a08f-31baf3126380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/katalon-analytics/docs/overview.html</value>
      <webElementGuid>b0063cc3-fb93-4914-9478-3eb4c0563d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon TestOps</value>
      <webElementGuid>ac1d65ba-a9e7-4659-842f-7b961fd1f690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jsTOCHorizontal&quot;)/li[2]/a[1]</value>
      <webElementGuid>3286a61b-68a2-4f3b-b40d-e4e91cac02cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='jsTOCHorizontal']/li[2]/a</value>
      <webElementGuid>035f2f58-1348-4027-b53f-c4bdc0176fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Katalon TestOps')]</value>
      <webElementGuid>dcb83153-4b6c-4ea7-a905-ce10f43fa8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Studio'])[1]/following::a[1]</value>
      <webElementGuid>dee41739-297e-45f9-9c40-ffaf57f224be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[2]</value>
      <webElementGuid>2e393f4e-eca4-4dbb-8605-0d29c3bc9e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plugins'])[1]/preceding::a[1]</value>
      <webElementGuid>f35bd0b1-10af-4c86-9cc6-ef10ca07e6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[1]/preceding::a[2]</value>
      <webElementGuid>cd44a61d-8863-4eb2-a82a-43acdc2034fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Katalon TestOps']/parent::*</value>
      <webElementGuid>6fc0b804-1dbe-4793-8cf2-5a0f7ad081a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/katalon-analytics/docs/overview.html')]</value>
      <webElementGuid>583b3a4a-0e43-4bb8-9023-35897ab85bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>6ee78470-0f25-443f-b4eb-322fb9c9febf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/katalon-analytics/docs/overview.html' and (text() = 'Katalon TestOps' or . = 'Katalon TestOps')]</value>
      <webElementGuid>28f85797-e4b4-4170-8fbe-df74542a739a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
