<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Videos</name>
   <tag></tag>
   <elementGuidId>98320ac1-b170-4817-9069-5c38a9c0f0c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='jsTOCHorizontal']/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b5714b6f-fd96-4ed7-a192-2641261e2301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/katalon-studio/videos/index.html</value>
      <webElementGuid>53be49fd-6976-4cd4-9d81-35d749d22157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>825bb6b8-d907-4fa7-8a09-00b097e061ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jsTOCHorizontal&quot;)/li[4]/a[1]</value>
      <webElementGuid>7d150563-6066-49cf-a230-097eabebcc0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='jsTOCHorizontal']/li[4]/a</value>
      <webElementGuid>5f3b0831-cb97-4ba7-835c-20f6b5814f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Videos')]</value>
      <webElementGuid>b49cf97e-ed11-4ec2-bc36-76210829f4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plugins'])[1]/following::a[1]</value>
      <webElementGuid>162d3049-a68a-4dc9-a919-c09a40f32f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon TestOps'])[1]/following::a[2]</value>
      <webElementGuid>30ee8464-67f1-4f29-af1a-46ce8d41f197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academy'])[1]/preceding::a[1]</value>
      <webElementGuid>901def65-c555-4e7d-9b7b-55659713072e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/preceding::a[2]</value>
      <webElementGuid>965c516c-2062-4a5b-ba72-6eb7e0e6d616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Videos']/parent::*</value>
      <webElementGuid>ea4a84c7-4b02-4b64-b9fe-f5b42fbd4673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/katalon-studio/videos/index.html')]</value>
      <webElementGuid>c214ae73-c2c5-42e5-b7c9-44d7b4cc7b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>084e81ee-7b6a-40c8-9e35-f0ba17f7a34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/katalon-studio/videos/index.html' and (text() = 'Videos' or . = 'Videos')]</value>
      <webElementGuid>6d9f6257-3c49-45f7-b4cc-961ab21254ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
